name: build
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build_and_test:
    name: test_ci
    uses: ./.github/workflows/reusable_build.yaml
    with:
      # NOTE: Avoid adding comments in the packages lines, this can break some of the called scripts in github actions
      # NOTE: Build upto rmf_fleet_adapter_python and rmf_visualization to cover all core open-rmf packages.
      packages: |
        rmf_fleet_adapter_python
        rmf_visualization
