name: build
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build_and_test:
    name: rmf_traffic_editor
    uses: ./.github/workflows/reusable_build.yaml
    with:
      # NOTE: Avoid adding comments in the packages lines, this can break some of the called scripts in github actions
      # NOTE: Using rmf_utils just for workflow testing porposes
      packages: |
        rmf_utils
