name: asan
on:
  workflow_call:
    inputs:
      packages:
        description: package names to build
        required: true
        type: string
      dist-matrix:
        description: dist matrix to build
        required: false
        type: string
        default: |
          [{"ros_distribution": "humble",
            "ubuntu_distribution": "jammy"},
          {"ros_distribution": "iron",
            "ubuntu_distribution": "jammy"},
          {"ros_distribution": "jazzy",
            "ubuntu_distribution": "noble"},
          {"ros_distribution": "rolling",
            "ubuntu_distribution": "noble"}]
jobs:
  asan:
    name: asan
    uses: ./.github/workflows/reusable_build.yaml
    with:
      dist-matrix: ${{inputs.dist-matrix}}
      packages: ${{inputs.packages}}
      mixin: asan
